name: Build UserLogin

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '1.8'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install FastLogin.jar to local Maven repo
        run: mvn install:install-file -Dfile=lib/fastlogin.jar -DgroupId=com.github.games647 -DartifactId=fastlogin -Dversion=1.10 -Dpackaging=jar

      - name: Build with Maven
        run: mvn clean package

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: UserLogin-jar
          path: target/*.jar
